version: "3.3"
services:
  db:
    image: postgres:13
    volumes:
      - ./db-data/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks: 
      - meal_wheel
  app:
    build: 
      context: .
      dockerfile: docker/Dockerfile.app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks: 
      - meal_wheel
    stdin_open: true
    tty: true
networks:
  meal_wheel:
