version: '3.3'

volumes: 
  db-data: 

services: 
  db: 
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
  
  app:
    build:
      context: .
      dockerfile: docker/web/Dockerfile.app
      args:
        RAILS_ROOT: ${RAILS_ROOT}
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    environment:
      RAILS_ENV: 'production'
      RAILS_ROOT: ${RAILS_ROOT}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    image: meal_wheel.prod:1.0.0
    restart: unless-stopped

  # web:
  #   build:
  #     context: .
  #     dockerfile: docker/web/Dockerfile.web
  #     args: RAILS_ROOT: ${RAILS_ROOT}
  #   depends_on: 
  #     - app
  #   ports:
  #     # PiHole is currently using port 80
  #     - 81:80
  #   environment: 
  #     - RAILS_ROOT
