version: '3.3'

volumes: 
  db-data: 

services: 
  db: 
    volumes:
      - db-data:/var/lib/postgresql/data
  
  app:
    build:
      context: .
      dockerfile: docker/web/Dockerfile.app
      args:
        RALS_ROOT: ${RAILS_ROOT}
      
    environment:
      RAILS_ENV: 'production'
    image: meal_wheel.prod:1.0.0

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile.web
    depends_on: 
      - app
    ports:
      # PiHole is currently using port 80
      - 81:80
    environment: 
      - ROOT
