version: "3.3"
services:
  db:
    image: postgres:13
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  app:
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        RALS_ROOT: ${RAILS_ROOT}
        # RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:${RAILS_ROOT}
    ports:
      - 3000:3000
    depends_on:
      - db
    environment: 
      - RAILS_ROOT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    image: meal_wheel:1.0.0
    stdin_open: true
    tty: true
